### ISSUE TITLE
卡片方面

### ISSUE THREAD

**Issue by 664697221** [Haisyer/TransFireBot#111]
大佬想问下卡片消息图片怎么写呀

**Comment by Haisyer** [comment]
FYI

https://open.imdodo.com/dev/api/card.html#图片

**Comment by 664697221** [comment]
试了没有用，主要是不会代码，可以举个例子吗

**Comment by Haisyer** [comment]
I don't exactly appreciate what kind of example you need. 
Perhaps you can refer to the code content of this project and the following project: [https://github.com/dodo-open/dodo-open-net](url).
You'd better learn some programming skills to accomplish your expectations.
