### ISSUE TITLE
update for net8.0？

### ISSUE THREAD

**Issue by fanyue1117** [Haisyer/TransFireBot#113]
请问有更新net8.0的支持吗？PKhex现在是8.0的编译，不能正常更新pk数据库了

**Comment by Haisyer** [comment]
Yes, we have support for .NET 8.0, but in order to avoid being misused by some unsuspecting people, it will not be public in the first time and the  code will be submitted in the near future.

**Comment by fanyue1117** [comment]
I want to use the latest version. Can you share it? thanks

**Comment by Haisyer** [comment]
Sorry. I'm on vacation. You can Ask my friend for the latest version.
The QQ number is 254808868.
I hope he can help you.

**Comment by fanyue1117** [comment]
Thanks, but this person has not responded. Perhaps you can inform your friend.
