### ISSUE TITLE
How to update the new pokemon data into Bot?

### ISSUE THREAD

**Issue by ZhuSeans** [Haisyer/TransFireBot#119]
Hi Haisyer 🙂  ,  I need your help that how to update the new pokemon data into the bot ?  For example,  the latest official strongest Empoleon.    Could you give some help? Thanks in advance！  

嗨Haisyer🙂 , 请问一下如何将官方新更新的宝可梦数据更新到机器人中？例如最新官方最强之证的帝王企鹅。你能帮助一下吗？非常感谢！

**Comment by Haisyer** [comment]
You should update the ALM and pk core from pkhex to fix the latest game

**Comment by ZhuSeans** [comment]
May I know how to update the ALM and PKHeX Core？  Could Haisyer give some help and thanks in advance？

**Comment by easyworld** [comment]
https://github.com/kwsch/SysBot.NET/wiki/Updating-PKHeX-Core-and-ALM
