### ISSUE TITLE
关于sv raid功能的咨询

### ISSUE THREAD

**Issue by zbyshuai** [Haisyer/TransFireBot#88]
请问 sv raid 该功能目前是处于未开完的状态吗？因为我测试该功能，一方面该功能并没有办法将房间号码发送到对应的dodo频道上，且查看源码时并未发现相关的操作指令。
另外，在自动打坑的时候，只能自动完成一场战斗，之后并不会重启游戏，读取存档达到反复开闪车的效果。

还是说我的使用方法不对呢？如果是的话，请问有相关的使用教程吗？

**Comment by Haisyer** [comment]
There is currently no update for raidbot, and it will be updated in the future when idle.
